package provider

import (
	"context"
	"net/http"
	"slices"

	"beryju.io/gravity/api"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// The defaults below mirror the values Gravity falls back to when a role has
// no stored configuration, so that a resource with no attributes set is a
// no-op rather than a reset.

func resourceRoleDNS() *schema.Resource {
	return roleConfigResource[api.DnsRoleConfig]{
		name:        "dns",
		description: "Configuration of the DNS role.",
		schema: map[string]*schema.Schema{
			"port": {
				Type:     schema.TypeInt,
				Optional: true,
				Default:  53,
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.DnsRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesDnsAPI.DnsGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.DnsRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.DnsRoleConfig) (*http.Response, error) {
			return c.client.RolesDnsAPI.DnsPutRoleConfig(ctx).
				DnsAPIRoleConfigInput(api.DnsAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.DnsRoleConfig {
			return api.DnsRoleConfig{
				Port: api.PtrInt32(int32(d.Get("port").(int))),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.DnsRoleConfig) {
			setWrapper(d, "port", int32Value(cfg.Port))
		},
	}.resource()
}

func resourceRoleDHCP() *schema.Resource {
	return roleConfigResource[api.DhcpRoleConfig]{
		name:        "dhcp",
		description: "Configuration of the DHCP role.",
		schema: map[string]*schema.Schema{
			"port": {
				Type:     schema.TypeInt,
				Optional: true,
				Default:  67,
			},
			"lease_negotiate_timeout": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     30,
				Description: "How long to wait for other instances to respond before offering a lease, in seconds.",
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.DhcpRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesDhcpAPI.DhcpGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.DhcpRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.DhcpRoleConfig) (*http.Response, error) {
			return c.client.RolesDhcpAPI.DhcpPutRoleConfig(ctx).
				DhcpAPIRoleConfigInput(api.DhcpAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.DhcpRoleConfig {
			return api.DhcpRoleConfig{
				Port:                  api.PtrInt32(int32(d.Get("port").(int))),
				LeaseNegotiateTimeout: api.PtrInt32(int32(d.Get("lease_negotiate_timeout").(int))),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.DhcpRoleConfig) {
			setWrapper(d, "port", int32Value(cfg.Port))
			setWrapper(d, "lease_negotiate_timeout", int32Value(cfg.LeaseNegotiateTimeout))
		},
	}.resource()
}

func resourceRoleAPI() *schema.Resource {
	return roleConfigResource[api.ApiRoleConfig]{
		name: "api",
		description: "Configuration of the API role. Note that changing `port` or " +
			"`listen_override` changes the endpoint this provider itself talks to.",
		schema: map[string]*schema.Schema{
			"port": {
				Type:     schema.TypeInt,
				Optional: true,
				Default:  8008,
			},
			"listen_override": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Override the address the API listens on.",
			},
			"session_duration": {
				Type:             schema.TypeString,
				Optional:         true,
				Description:      "How long a web session stays valid, as a Go duration (e.g. `168h`).",
				ValidateDiagFunc: validateDuration,
			},
			"cookie_secret": {
				Type:      schema.TypeString,
				Optional:  true,
				Computed:  true,
				Sensitive: true,
				Description: "Key used to sign session cookies. Generated by the server when " +
					"left unset; changing it invalidates every existing session.",
			},
			"oidc": {
				Type:        schema.TypeList,
				Optional:    true,
				MaxItems:    1,
				Description: "OIDC provider used to authenticate to the web interface.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"client_id": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"client_secret": {
							Type:      schema.TypeString,
							Optional:  true,
							Sensitive: true,
						},
						"issuer": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"redirect_url": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"scopes": {
							Type:     schema.TypeList,
							Optional: true,
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"token_username_field": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Claim in the ID token to take the username from.",
						},
					},
				},
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.ApiRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesApiAPI.ApiGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.ApiRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.ApiRoleConfig) (*http.Response, error) {
			return c.client.RolesApiAPI.ApiPutRoleConfig(ctx).
				ApiAPIRoleConfigInput(api.ApiAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.ApiRoleConfig {
			cfg := api.ApiRoleConfig{
				Port:            api.PtrInt32(int32(d.Get("port").(int))),
				ListenOverride:  api.PtrString(d.Get("listen_override").(string)),
				SessionDuration: api.PtrString(d.Get("session_duration").(string)),
				CookieSecret:    api.PtrString(d.Get("cookie_secret").(string)),
			}
			for _, raw := range d.Get("oidc").([]interface{}) {
				v := raw.(map[string]interface{})
				cfg.Oidc = &api.TypesOIDCConfig{
					ClientID:           api.PtrString(v["client_id"].(string)),
					ClientSecret:       api.PtrString(v["client_secret"].(string)),
					Issuer:             api.PtrString(v["issuer"].(string)),
					RedirectURL:        api.PtrString(v["redirect_url"].(string)),
					Scopes:             sliceToString(v["scopes"].([]interface{})),
					TokenUsernameField: api.PtrString(v["token_username_field"].(string)),
				}
			}
			return cfg
		},
		toState: func(d *schema.ResourceData, cfg api.ApiRoleConfig) {
			setWrapper(d, "port", int32Value(cfg.Port))
			setWrapper(d, "listen_override", stringValue(cfg.ListenOverride))
			setWrapper(d, "session_duration", stringValue(cfg.SessionDuration))
			setWrapper(d, "cookie_secret", stringValue(cfg.CookieSecret))
			setWrapper(d, "oidc", flattenOIDC(cfg.Oidc))
		},
		settled: func(sent api.ApiRoleConfig, got api.ApiRoleConfig) bool {
			// The server generates a cookie secret of its own when it is sent
			// an empty one, so an empty request matches whatever comes back.
			if s := stringValue(sent.CookieSecret); s != "" && s != stringValue(got.CookieSecret) {
				return false
			}
			return int32Value(sent.Port) == int32Value(got.Port) &&
				stringValue(sent.ListenOverride) == stringValue(got.ListenOverride) &&
				stringValue(sent.SessionDuration) == stringValue(got.SessionDuration) &&
				oidcEqual(sent.Oidc, got.Oidc)
		},
	}.resource()
}

func oidcEqual(a *api.TypesOIDCConfig, b *api.TypesOIDCConfig) bool {
	if a == nil || b == nil {
		return (a == nil) == (b == nil)
	}
	return stringValue(a.ClientID) == stringValue(b.ClientID) &&
		stringValue(a.ClientSecret) == stringValue(b.ClientSecret) &&
		stringValue(a.Issuer) == stringValue(b.Issuer) &&
		stringValue(a.RedirectURL) == stringValue(b.RedirectURL) &&
		stringValue(a.TokenUsernameField) == stringValue(b.TokenUsernameField) &&
		slices.Equal(stringSlice(a.Scopes), stringSlice(b.Scopes))
}

func flattenOIDC(o *api.TypesOIDCConfig) []interface{} {
	if o == nil {
		return []interface{}{}
	}
	return []interface{}{
		map[string]interface{}{
			"client_id":            stringValue(o.ClientID),
			"client_secret":        stringValue(o.ClientSecret),
			"issuer":               stringValue(o.Issuer),
			"redirect_url":         stringValue(o.RedirectURL),
			"scopes":               stringSlice(o.Scopes),
			"token_username_field": stringValue(o.TokenUsernameField),
		},
	}
}

func resourceRoleBackup() *schema.Resource {
	return roleConfigResource[api.BackupRoleConfig]{
		name:        "backup",
		description: "Configuration of the backup role, which snapshots the cluster to S3-compatible storage.",
		schema: map[string]*schema.Schema{
			"endpoint": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"bucket": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"path": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Prefix within the bucket to write backups to.",
			},
			"access_key": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"secret_key": {
				Type:      schema.TypeString,
				Optional:  true,
				Sensitive: true,
			},
			"cron_expr": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "0 */24 * * *",
				Description: "Cron expression describing when backups run.",
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.BackupRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesBackupAPI.BackupGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.BackupRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.BackupRoleConfig) (*http.Response, error) {
			return c.client.RolesBackupAPI.BackupPutRoleConfig(ctx).
				BackupAPIRoleConfigInput(api.BackupAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.BackupRoleConfig {
			return api.BackupRoleConfig{
				Endpoint:  api.PtrString(d.Get("endpoint").(string)),
				Bucket:    api.PtrString(d.Get("bucket").(string)),
				Path:      api.PtrString(d.Get("path").(string)),
				AccessKey: api.PtrString(d.Get("access_key").(string)),
				SecretKey: api.PtrString(d.Get("secret_key").(string)),
				CronExpr:  api.PtrString(d.Get("cron_expr").(string)),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.BackupRoleConfig) {
			setWrapper(d, "endpoint", stringValue(cfg.Endpoint))
			setWrapper(d, "bucket", stringValue(cfg.Bucket))
			setWrapper(d, "path", stringValue(cfg.Path))
			setWrapper(d, "access_key", stringValue(cfg.AccessKey))
			setWrapper(d, "secret_key", stringValue(cfg.SecretKey))
			setWrapper(d, "cron_expr", stringValue(cfg.CronExpr))
		},
	}.resource()
}

func resourceRoleDiscovery() *schema.Resource {
	return roleConfigResource[api.DiscoveryRoleConfig]{
		name:        "discovery",
		description: "Configuration of the discovery role.",
		schema: map[string]*schema.Schema{
			"enabled": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  true,
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.DiscoveryRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesDiscoveryAPI.DiscoveryGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.DiscoveryRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.DiscoveryRoleConfig) (*http.Response, error) {
			return c.client.RolesDiscoveryAPI.DiscoveryPutRoleConfig(ctx).
				DiscoveryAPIRoleConfigInput(api.DiscoveryAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.DiscoveryRoleConfig {
			return api.DiscoveryRoleConfig{
				Enabled: api.PtrBool(d.Get("enabled").(bool)),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.DiscoveryRoleConfig) {
			setWrapper(d, "enabled", boolValue(cfg.Enabled))
		},
	}.resource()
}

func resourceRoleMonitoring() *schema.Resource {
	return roleConfigResource[api.MonitoringRoleConfig]{
		name:        "monitoring",
		description: "Configuration of the monitoring role, which serves health checks and metrics.",
		schema: map[string]*schema.Schema{
			"port": {
				Type:     schema.TypeInt,
				Optional: true,
				Default:  8009,
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.MonitoringRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesMonitoringAPI.MonitoringGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.MonitoringRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.MonitoringRoleConfig) (*http.Response, error) {
			return c.client.RolesMonitoringAPI.MonitoringPutRoleConfig(ctx).
				MonitoringAPIRoleConfigInput(api.MonitoringAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.MonitoringRoleConfig {
			return api.MonitoringRoleConfig{
				Port: api.PtrInt32(int32(d.Get("port").(int))),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.MonitoringRoleConfig) {
			setWrapper(d, "port", int32Value(cfg.Port))
		},
	}.resource()
}

func resourceRoleTFTP() *schema.Resource {
	return roleConfigResource[api.TftpRoleConfig]{
		name:        "tftp",
		description: "Configuration of the TFTP role.",
		schema: map[string]*schema.Schema{
			"port": {
				Type:     schema.TypeInt,
				Optional: true,
				Default:  69,
			},
			"enable_local": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
				Description: "Serve files from the instance's local filesystem in addition to stored files.",
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.TftpRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesTftpAPI.TftpGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.TftpRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.TftpRoleConfig) (*http.Response, error) {
			return c.client.RolesTftpAPI.TftpPutRoleConfig(ctx).
				TftpAPIRoleConfigInput(api.TftpAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.TftpRoleConfig {
			return api.TftpRoleConfig{
				Port:        api.PtrInt32(int32(d.Get("port").(int))),
				EnableLocal: api.PtrBool(d.Get("enable_local").(bool)),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.TftpRoleConfig) {
			setWrapper(d, "port", int32Value(cfg.Port))
			setWrapper(d, "enable_local", boolValue(cfg.EnableLocal))
		},
	}.resource()
}

func resourceRoleTSDB() *schema.Resource {
	return roleConfigResource[api.TsdbRoleConfig]{
		name:        "tsdb",
		description: "Configuration of the TSDB role, which records metrics about the cluster.",
		schema: map[string]*schema.Schema{
			"enabled": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  true,
			},
			"expire": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     1800,
				Description: "How long recorded metrics are kept, in seconds.",
			},
			"scrape": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     30,
				Description: "Interval between metric collections, in seconds.",
			},
		},
		get: func(ctx context.Context, c *APIClient) (api.TsdbRoleConfig, *http.Response, error) {
			res, hr, err := c.client.RolesTsdbAPI.TsdbGetRoleConfig(ctx).Execute()
			if err != nil {
				return api.TsdbRoleConfig{}, hr, err
			}
			return res.Config, hr, nil
		},
		put: func(ctx context.Context, c *APIClient, cfg api.TsdbRoleConfig) (*http.Response, error) {
			return c.client.RolesTsdbAPI.TsdbPutRoleConfig(ctx).
				TsdbAPIRoleConfigInput(api.TsdbAPIRoleConfigInput{Config: cfg}).Execute()
		},
		toModel: func(d *schema.ResourceData) api.TsdbRoleConfig {
			return api.TsdbRoleConfig{
				Enabled: api.PtrBool(d.Get("enabled").(bool)),
				Expire:  api.PtrInt64(int64(d.Get("expire").(int))),
				Scrape:  api.PtrInt64(int64(d.Get("scrape").(int))),
			}
		},
		toState: func(d *schema.ResourceData, cfg api.TsdbRoleConfig) {
			setWrapper(d, "enabled", boolValue(cfg.Enabled))
			setWrapper(d, "expire", int64Value(cfg.Expire))
			setWrapper(d, "scrape", int64Value(cfg.Scrape))
		},
	}.resource()
}
