package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAPIToken() *schema.Resource {
	return &schema.Resource{
		Description: "API token for a Gravity user. The key is generated by the server and " +
			"can only be read at creation time, so importing a token recovers the user it " +
			"belongs to but not the key itself.",
		CreateContext: resourceAPITokenCreate,
		ReadContext:   resourceAPITokenRead,
		DeleteContext: resourceAPITokenDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{
			"username": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "User the token authenticates as.",
			},
			"key": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "The generated token.",
			},
		},
	}
}

func resourceAPITokenCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*APIClient)

	username := d.Get("username").(string)

	res, hr, err := c.client.RolesApiAPI.ApiPutTokens(ctx).Username(username).Execute()
	if err != nil {
		return httpToDiag(d, hr, err)
	}
	d.SetId(res.Key)
	setWrapper(d, "key", res.Key)
	return resourceAPITokenRead(ctx, d, m)
}

func resourceAPITokenRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	c := m.(*APIClient)

	// The API only lists tokens, so the matching key has to be found locally.
	res, hr, err := c.client.RolesApiAPI.ApiGetTokens(ctx).Execute()
	if err != nil {
		return httpToDiag(d, hr, err)
	}

	for _, token := range res.Tokens {
		if token.Key != d.Id() {
			continue
		}
		setWrapper(d, "username", token.Username)
		return diags
	}
	d.SetId("")
	return diags
}

func resourceAPITokenDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*APIClient)
	hr, err := c.client.RolesApiAPI.ApiDeleteTokens(ctx).Key(d.Id()).Execute()
	if err != nil {
		return httpToDiag(d, hr, err)
	}
	return diag.Diagnostics{}
}
