name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "beta"
          - "rc"
          - "latest"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - uses: ./.github/actions/setup-gravity
        id: gravity
      - env:
          TF_ACC: "1"
          GRAVITY_URL: ${{ steps.gravity.outputs.http_url }}
          GRAVITY_TOKEN: ${{ steps.gravity.outputs.admin_token }}
        timeout-minutes: 10
        run: |
          go test -timeout 0 -v -race -coverprofile=coverage.txt -covermode=atomic -cover ./internal/provider/
      - name: gravity logs
        if: ${{ always() }}
        run: |
          docker logs ${{ steps.gravity.outputs.server_container_id }}
      - if: ${{ always() }}
        uses: codecov/codecov-action@v5
